# Generated by Django 4.2.4 on 2023-08-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_user_rooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rooms',
            new_name='Room',
        ),
    ]
